name: CI pipeline

on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      - '.github/**'
env:
  RELEASE_VERSION: v2.5.0

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."