name: CI pipeline

on:
  push:
    branches:
      - 'develop'

env:
  RELEASE_VERSION: v1.0.0

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show current path
        run: |
          pwd
          ls -la
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mock-app-image-updater:${{ env.RELEASE_VERSION }}-${{ github.ref_name }}